const express = require('express');
const r = express.Router();
const { protect, authorize } = require('../middleware/authMiddleware');
const C = require('../controllers/substituteController');
r.post('/request', protect, authorize('teacher'), C.requestSubstitute);
r.get('/my', protect, authorize('teacher'), C.getMyRequests);
r.patch('/:id/accept', protect, authorize('teacher'), C.acceptRequest);
r.patch('/:id/decline', protect, authorize('teacher'), C.declineRequest);
r.get('/all', protect, authorize('hod', 'principal'), C.getAllSubRequests);
r.patch('/:id/hod-approve', protect, authorize('hod'), C.hodApproveSubstitute);
r.patch('/:id/principal-approve', protect, authorize('principal'), C.principalApproveSubstitute);
module.exports = r;
