import { useCallback, useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import API from '../api';

const TYPES = [['casual','Casual'],['sick','Sick'],['emergency','Emergency'],['paternity/maternity','Paternity / Maternity']];
const CONFIRMED = ['accepted','hod_approved','principal_approved'];
const date = d => d ? String(d).slice(0,10) : '';
const fmt = d => d ? new Date(date(d)+'T12:00:00Z').toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'}) : '—';
const days = (a,b) => a && b ? Math.max(0,Math.round((Date.parse(b)-Date.parse(a))/86400000)+1) : 0;
const covered = r => CONFIRMED.includes(r.status) && !!r.substituteTeacher;
const progress = l => { const rs=l.substituteRequests||[]; return {required:rs.length,accepted:rs.filter(covered).length,complete:rs.length>0&&rs.every(covered)}; };
const error = e => e.response?.data?.message || e.message || 'Request failed';
const field = {width:'100%',boxSizing:'border-box',padding:'10px 12px',border:'1px solid #D1D5DB',borderRadius:8,background:'#F9FAFB',fontSize:14};
const card = {background:'#fff',border:'1px solid #E5E7EB',borderRadius:12,padding:20,marginBottom:16};
const button = {padding:'10px 18px',border:0,borderRadius:8,background:'#4F46E5',color:'#fff',fontWeight:700,cursor:'pointer'};
const label = {display:'block',fontSize:11,fontWeight:700,color:'#6B7280',textTransform:'uppercase',marginBottom:6};
const grid = {display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(min(100%,240px),1fr))',gap:12};
function Field({title,children}) { return <label style={{display:'block',minWidth:0}}><span style={label}>{title}</span>{children}</label>; }
function Period({r}) { return <div style={{padding:'9px 12px',background:'#F9FAFB',borderRadius:8,marginTop:6,fontSize:13}}><b>{fmt(r.date)} · Period {r.periodNumber}</b> · {r.subject} · Class {r.className}<div style={{color:'#6B7280',marginTop:3}}>{r.startTime}–{r.endTime} · {r.substituteTeacher?.name || 'Awaiting substitute'}</div></div>; }
export default function WorkflowDashboard() {
 const navigate=useNavigate();
 const user=JSON.parse(localStorage.getItem('user')||'{}');
 const role=user.role||'teacher';
 const [tab,setTab]=useState('dashboard');
 const [leaves,setLeaves]=useState([]),[requests,setRequests]=useState([]),[balance,setBalance]=useState(null);
 const [form,setForm]=useState({startDate:'',endDate:'',leaveType:'casual'});
 const [reasons,setReasons]=useState({}),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const load=useCallback(async()=>{const admin=role!=='teacher';const [l,s]=await Promise.all([API.get(admin?'/leaves/all':'/leaves/my'),API.get(admin?'/substitutes/all':'/substitutes/my')]);setLeaves(l.data);setRequests(s.data);if(!admin)setBalance((await API.get('/leaves/balance')).data);},[role]);
 useEffect(()=>{load().catch(e=>setMessage(error(e)));},[load]);
 async function act(fn){if(busy)return;setBusy(true);setMessage('');try{const result=await fn();await load();setMessage(result?.data?.message||'Saved successfully.');}catch(e){setMessage(error(e));}finally{setBusy(false);}}
 const logout=()=>{localStorage.removeItem('token');localStorage.removeItem('user');navigate('/login');};
 // The API returns newest leaves first. Only one ready application is displayed;
 // other records remain available in history and are never merged or deleted.
 const pending=leaves.filter(l=>l.status==='substitute_confirmed'&&progress(l).complete).slice(0,1);
 const active=leaves.filter(l=>['coverage_pending','substitute_confirmed'].includes(l.status));
 const tabs=role==='teacher'?[['dashboard','Dashboard'],['request','Request Substitute'],['substitutes',`Substitutes${requests.length?' ('+requests.length+')':''}`]]:[['dashboard','Dashboard'],['review','Leave review'],['assignments','Substitutes']];
 return <main style={{maxWidth:980,margin:'0 auto',padding:'24px 16px',fontFamily:'-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif',color:'#111827'}}>
 <header style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:16,marginBottom:24}}><div><h1 style={{fontSize:22,margin:0}}>Leave Management</h1><p style={{fontSize:13,color:'#6B7280',margin:'4px 0'}}>{user.name} · <span style={{color:'#4F46E5'}}>{role}</span></p></div><button onClick={logout} style={{...button,background:'#fff',color:'#374151',border:'1px solid #E5E7EB'}}>Log out</button></header>
 <nav style={{display:'flex',gap:4,flexWrap:'wrap',background:'#F3F4F6',padding:4,borderRadius:10,width:'fit-content',marginBottom:24}}>{tabs.map(([key,name])=><button key={key} onClick={()=>setTab(key)} style={{...button,background:tab===key?'#fff':'transparent',color:tab===key?'#4F46E5':'#6B7280',boxShadow:tab===key?'0 1px 4px #0002':'none'}}>{name}</button>)}</nav>
 {message&&<div role="status" style={{...card,background:'#EEF2FF',color:'#3730A3'}}>{message}</div>}
 {role==='teacher'&&<>
 {tab==='dashboard'&&<>
 {pending.map(l=><section key={l._id} style={{...card,background:'#F5F3FF',border:'2px solid #4F46E5'}}><h3 style={{margin:'0 0 6px',color:'#4C1D95'}}>Action needed: Fill your leave application</h3><p style={{fontSize:13,color:'#6B7280'}}>All {progress(l).required} required period(s) are covered. Fill in your leave details and submit to HOD.</p><div style={grid}><Field title="Start date"><input style={field} type="date" value={date(l.startDate)} readOnly/></Field><Field title="End date"><input style={field} type="date" value={date(l.endDate)} readOnly/></Field><Field title="Leave type"><select style={field} value={l.leaveType} disabled>{TYPES.map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></Field></div><p style={{background:'#fff',border:'1px solid #C4B5FD',borderRadius:8,padding:10,fontSize:12}}><b>{days(date(l.startDate),date(l.endDate))} day(s)</b> · {fmt(l.startDate)} → {fmt(l.endDate)}</p><Field title="Reason *"><textarea style={{...field,resize:'vertical'}} rows={2} placeholder="Brief reason for your leave..." value={reasons[l._id]||''} onChange={e=>setReasons(old=>({...old,[l._id]:e.target.value}))}/></Field><button style={{...button,width:'100%',marginTop:12}} disabled={busy||!reasons[l._id]?.trim()} onClick={()=>act(()=>API.patch(`/leaves/${l._id}/details`,{reason:reasons[l._id]}))}>✓ Submit leave application → HOD</button></section>)}
 {balance&&<div style={{...grid,marginBottom:20}}>{[['Jan – Jun',balance.firstHalfTotal-balance.firstHalfUsed,`${balance.firstHalfUsed} used of ${balance.firstHalfTotal}`,'#EDE9FE'],['Jul – Dec',balance.secondHalfTotal-balance.secondHalfUsed,`${balance.secondHalfUsed} used of ${balance.secondHalfTotal}`,'#D1FAE5'],['Total remaining',balance.firstHalfTotal+balance.secondHalfTotal-balance.firstHalfUsed-balance.secondHalfUsed,'Available this year','#DBEAFE'],['Privileged Leaves',balance.privilegedLeaves||0,'Carried over','#FEF3C7']].map(([name,value,sub,bg])=><div key={name} style={{background:bg,borderRadius:10,padding:16}}><div style={{fontSize:11,fontWeight:700}}>{name.toUpperCase()}</div><div style={{fontSize:30,fontWeight:800}}>{value}</div><div style={{fontSize:11,color:'#6B7280'}}>{sub}</div></div>)}</div>}
 <h3>Leave history</h3>{leaves.length===0?<p>No leave applications yet.</p>:leaves.map(l=>{const p=progress(l);return <article key={l._id} style={card}><b>{fmt(l.startDate)} → {fmt(l.endDate)} · {l.leaveType}</b><p style={{fontSize:13}}>Status: {l.status.replaceAll('_',' ')} · Coverage: <b>{p.accepted}/{p.required}</b></p>{l.status==='coverage_pending'&&<p style={{color:'#92400E',fontSize:13}}>Waiting for {p.required-p.accepted} period(s). The leave form unlocks only after every period is covered.</p>}{(l.substituteRequests||[]).map(r=><Period key={r._id} r={r}/>)}{l.status==='rejected'&&<p>Rejection reason: {l.rejectionReason||'Not provided'}</p>}</article>;})}
 </>}
 {tab==='request'&&<div style={grid}><section style={card}><h3>Request a substitute</h3><p style={{fontSize:13,color:'#6B7280'}}>Select your leave dates and type. The system creates coverage requests for every scheduled period across the entire date range.</p><form onSubmit={e=>{e.preventDefault();act(()=>API.post('/substitutes/request',form));}}><div style={grid}><Field title="Start date *"><input style={field} type="date" required value={form.startDate} onChange={e=>setForm({...form,startDate:e.target.value})}/></Field><Field title="End date *"><input style={field} type="date" required min={form.startDate} value={form.endDate} onChange={e=>setForm({...form,endDate:e.target.value})}/></Field></div><div style={{marginTop:14}}><Field title="Leave type *"><select style={field} value={form.leaveType} onChange={e=>setForm({...form,leaveType:e.target.value})}>{TYPES.map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></Field></div>{form.startDate&&form.endDate&&<div style={{background:'#EDE9FE',border:'1px solid #C4B5FD',borderRadius:10,padding:14,margin:'16px 0',fontSize:13}}><b>Request summary</b><p>{days(form.startDate,form.endDate)} day(s) · {fmt(form.startDate)} → {fmt(form.endDate)}</p>All scheduled periods will require substitute acceptance.</div>}<button style={{...button,width:'100%',marginTop:12}} disabled={busy||!form.startDate||!form.endDate||form.endDate<form.startDate}>Send substitute requests for all periods</button></form></section><section style={{...card,background:'#F9FAFB'}}><h3>How it works</h3>{['Fill dates & leave type','Requests created for every scheduled period','Each period is accepted by one available teacher','All coverage confirmed → leave form unlocks','HOD reviews the submitted leave','Principal gives final approval'].map((s,i)=><p key={s} style={{fontSize:13,margin:'18px 0'}}><b style={{color:'#4F46E5',marginRight:10}}>{i+1}</b>{s}</p>)}</section></div>}
 {tab==='substitutes'&&<section><h3>Substitute requests for me</h3><p style={{fontSize:13,color:'#6B7280'}}>Only open requests are shown. Once another teacher accepts a period, it is no longer available.</p>{requests.length===0?<p>No open requests.</p>:requests.map(r=><article key={r._id} style={card}><b>{r.absentTeacher?.name} · {fmt(r.date)} · Period {r.periodNumber}</b><p style={{fontSize:13}}>{r.subject} · Class {r.className} · {r.startTime}–{r.endTime}</p><p style={{fontSize:13}}>Leave: {fmt(r.leave?.startDate)} → {fmt(r.leave?.endDate)} · {r.leave?.leaveType}</p><button style={button} disabled={busy} onClick={()=>act(()=>API.patch(`/substitutes/${r._id}/accept`))}>Accept</button>{' '}<button style={{...button,background:'#F3F4F6',color:'#374151'}} disabled={busy} onClick={()=>act(()=>API.patch(`/substitutes/${r._id}/decline`))}>Decline</button></article>)}</section>}
 </>}
 {role!=='teacher'&&<>
 {tab==='dashboard'&&<section style={card}><h3>Leave Management</h3><p>Review pending leave applications and substitute assignments using the tabs above.</p><p>{leaves.filter(l=>l.status===(role==='hod'?'submitted':'hod_approved')).length} leave application(s) awaiting your review.</p></section>}
 {tab==='review'&&<section><h3>Leave review</h3>{leaves.filter(l=>l.status===(role==='hod'?'submitted':'hod_approved')).map(l=>{const p=progress(l);return <article key={l._id} style={card}><b>{l.teacher?.name} · {fmt(l.startDate)} → {fmt(l.endDate)}</b><p>{l.leaveType} · {l.reason}</p><p>Coverage: {p.accepted}/{p.required}</p>{(l.substituteRequests||[]).map(r=><Period key={r._id} r={r}/>)}<div style={{marginTop:12}}><button style={button} disabled={busy||!p.complete} onClick={()=>act(()=>API.patch(`/leaves/${l._id}/${role==='hod'?'hod-approve':'principal-approve'}`))}>Approve</button>{' '}<button style={{...button,background:'#FEE2E2',color:'#991B1B'}} disabled={busy} onClick={()=>{const reason=window.prompt('Reason for rejection');if(reason?.trim())act(()=>API.patch(`/leaves/${l._id}/reject`,{reason}));}}>Reject</button></div></article>;})}<h3>All leave statuses</h3>{leaves.map(l=><p key={l._id}>{l.teacher?.name} · {fmt(l.startDate)} → {fmt(l.endDate)} · {l.status}</p>)}</section>}
 {tab==='assignments'&&<section><h3>Substitute assignments</h3>{requests.filter(r=>r.status===(role==='hod'?'accepted':'hod_approved')).map(r=><article key={r._id} style={card}><Period r={r}/><button style={{...button,marginTop:12}} disabled={busy} onClick={()=>act(()=>API.patch(`/substitutes/${r._id}/${role==='hod'?'hod-approve':'principal-approve'}`))}>Confirm assignment</button></article>)}</section>}
 </>}
 </main>;
}
